osx_image: xcode10.2
language: objective-c
branches:
  only:
    - master
notifications:
  email: false
script:
- xcodebuild -workspace SwiftChaining_mac.xcworkspace -scheme SwiftChaining_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
- xcodebuild -workspace SwiftChaining_ios.xcworkspace -scheme SwiftChaining_ios_tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' clean test
- pod lib lint
